---
- name: Get rpm
  get_url:
    url: https://collectors.sumologic.com/rest/download/rpm/64
    dest: /tmp/sumologic.rpm

- name: install sumologic rpm
  yum:
    name: '/tmp/sumologic.rpm'
    state: present

- name: put config file in place
  template:
    src: 'templates/user.properties.j2'
    dest: '/opt/SumoCollector/config/user.properties'
    owner: root
    group: sumologic_collector

- name: put sources file in place
  template:
    src: 'templates/sources.json.j2'
    dest: '/opt/SumoCollector/config/sources.json'
    owner: root
    group: sumologic_collector

- name: start service
  service:
    name: collector
    state: started
    enabled: yes
