---
- name: Get rpm
  get_url:
    url: https://collectors.sumologic.com/rest/download/rpm/64
    dest: /tmp/sumologic.rpm

- name: install sumologic rpm
  yum:
    name: '/tmp/sumologic.rpm'
    state: installed

- name: delete rpm file
  file:
    path: "/tmp/sumologic.rpm"
    state: absent
